### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by xpeuvr327** [KaruzoHikari/Revo-Launcher#84]
I wanted to test the upload feature, so I created a wii phone account. But i forgot the .com (in the email form i put user@gmail). I didn't receive any email, and when I want to create an account with my actual mail (user@gmail.com) it says "This mail is already used. Please choose another one, or connect to this account." But when I create use the Login option and put my actual email, it says "No account with this email was found." I'm using the apk launcher version if that matters.

**Comment by Stoutscientist** [comment]
Try using an email alias, ex. `youremail+1@gmail.com`
