### ISSUE TITLE
Faster loading (AND How To fix) @KaruzoHikari

### ISSUE THREAD

**Issue by GithubUser559** [KaruzoHikari/Revo-Launcher#86]
There is a problem on Wii phone. I have more than 60 channels and the app takes a long time to load. The app restarts itself and has to be loaded again. It's Annoying. HOW TO FIX? If you cannot `optimize` the load More,Add A Quick Menú Like Wii U With 10 apps.With the apps chosen by the user. And disable and enable the quick menu  in settings. With Skip banner AND fixing the skip banner sound error in themes. With the option of Skip banner in quick menu AND The normal menú Separately.With a Button of load the normal app  @KaruzoHikari Please fix This With Wii Phone 5.2 or 6.0. And With Skip banner Do not load banners for faster With the quick menu``  With a Lot of patience.                                   -The 
fans

**Comment by KaruzoHikari** [comment]
Revo Launcher 5.2 includes a way to start loading channels automatically on load. Along with low memory being turned on by default, I hope it helps you launch your app faster
